# docker-compose up -d --build - запуск docker
# http://localhost:8085
version: "3.9"

services:
  web:
    build:
      context: .                
      dockerfile: docker/php/Dockerfile
    container_name: my_site_web
    ports:
      - "8085:80"
    volumes:
       - ./dist:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: my_site_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
